Repository dojot/ansible-dojot, pull requests merged in 2020-07, with the labels that each got.

#39 Fix variable name
  roles/databases/postgres-ejbca/templates/postgres_statefulset.yaml.j2
Labels: Type:Bug

#40 Correct namespace in Grafana datasources
  roles/metrics/templates/grafana-dashboardDatasources.yaml
Labels: Type:Bug

#46 [feat] Add Kafka WS and x509 services
  deploy.yaml
  docs/vars.md
  inventories/example_local/group_vars/dojot-k8s/dojot.yaml
  local_storage_example/volumes/x509_identity_mgmt.yaml
  roles/apigw/templates/apigw_routes_config_map.yaml.j2
  roles/apigw/vars/main.yaml
  roles/databases/postgresql/defaults/main.yaml
  roles/databases/postgresql/templates/postgres_init_config_map.yaml.j2
  roles/databases/postgresql/templates/postgres_statefulset.yaml.j2
  roles/k2v-bridge/defaults/main.yaml
  roles/k2v-bridge/templates/k2v_bridge_cluster.yaml.j2
  roles/kafka-loopback/defaults/main.yaml
  roles/kafka-loopback/templates/kafka_loopback_cluster.yaml.j2
  roles/kafka-ws/defaults/main.yaml
  roles/kafka-ws/tasks/main.yaml
  roles/kafka-ws/templates/kafka_ws_deployment.yaml.j2
  roles/kafka-ws/templates/kafka_ws_redis_service.yaml.j2
  roles/kafka-ws/templates/kafka_ws_redis_statefulset.yaml.j2
  roles/kafka-ws/templates/kafka_ws_service.yaml.j2
  roles/kafka/templates/kafka_statefulset.yaml.j2
  roles/metrics/templates/grafana-dashboardDefinitions.yaml
  roles/metrics/templates/grafana-deployment.yaml
  roles/metrics/templates/prometheus-servicelprometheus.yaml
  roles/v2k-bridge/defaults/main.yaml
  roles/v2k-bridge/templates/v2k_bridge_cluster.yaml.j2
  roles/vernemq/defaults/main.yaml
  roles/vernemq/templates/z_vernemq_cluster.yaml.j2
  roles/x509-identity-mgmt/defaults/main.yaml
  roles/x509-identity-mgmt/tasks/main.yaml
  roles/x509-identity-mgmt/templates/x509_identity_mgmt_deployment.yaml.j2
  roles/x509-identity-mgmt/templates/x509_identity_mgmt_pvc.yaml.j2
  roles/x509-identity-mgmt/templates/x509_identity_mgmt_secrets.yaml.j2
  roles/x509-identity-mgmt/templates/x509_identity_mgmt_service.yaml.j2
Labels: Type:Feature

#43 Use of HAProxy as a load balancer
  balancer.yaml
  docs/vars.md
  inventories/example_local/hosts.yaml
  roles/haproxy/defaults/main.yaml
  roles/haproxy/handlers/main.yml
  roles/haproxy/tasks/main.yaml
  roles/haproxy/templates/haproxy.cfg.j2
Labels: Type:Enhancement

#44 Playbook for k8s cluster creation
  inventories/example_local/hosts.yaml
  k8s.yaml
  roles/k8s-cluster/all-nodes/defaults/main.yaml
  roles/k8s-cluster/all-nodes/handlers/main.yaml
  roles/k8s-cluster/all-nodes/tasks/main.yaml
  roles/k8s-cluster/master-node/defaults/main.yaml
  roles/k8s-cluster/master-node/tasks/main.yaml
  roles/k8s-cluster/master-node/templates/config.yaml.j2
  roles/k8s-cluster/worker-node/tasks/main.yaml
Labels: Type:Enhancement
