Repository dojot/ansible-dojot, pull requests merged in 2020-08, with the labels that each got.

#51 [enhance] Parameterize Node Affinity
  docs/vars.md
  inventories/example_local/group_vars/dojot-k8s/dojot.yaml
  local_storage_example/volumes/apigw.yaml
  local_storage_example/volumes/kafka.yaml
  local_storage_example/volumes/kafka_ws.yaml
  local_storage_example/volumes/minio.yaml
  local_storage_example/volumes/mongo.yaml
  local_storage_example/volumes/postgres.yaml
  local_storage_example/volumes/prometheus.yaml
  local_storage_example/volumes/storageclass.yaml
  local_storage_example/volumes/x509_identity_mgmt.yaml
  local_storage_example/volumes/zookeeper_data.yaml
  local_storage_example/volumes/zookeeper_log.yaml
  roles/apigw/templates/apigw_deployment.yaml.j2
  roles/apigw/templates/apigw_migration_job.yaml.j2
  roles/apigw/templates/apigw_migration_up_job.yaml.j2
  roles/apigw/templates/apigw_routes_config.yaml.j2
  roles/auth/templates/auth_deployment.yaml.j2
  roles/backstage/templates/backstage_deployment.yaml.j2
  roles/cron/templates/cron_deployment.yaml.j2
  roles/data-broker/templates/data_broker_deployment.yaml.j2
  roles/data-broker/templates/data_broker_redis_deployment.yaml.j2
  roles/data-manager/templates/data_manager_deployment.yaml.j2
  roles/databases/mongodb/templates/mongodb_statefulset.yaml.j2
  roles/databases/postgres-ejbca/defaults/main.yaml
  roles/databases/postgres-ejbca/tasks/main.yaml
  roles/databases/postgres-ejbca/templates/postgres_init_config_map.yaml.j2
  roles/databases/postgres-ejbca/templates/postgres_secret.yaml.j2
  roles/databases/postgres-ejbca/templates/postgres_service.yaml.j2
  roles/databases/postgres-ejbca/templates/postgres_statefulset.yaml.j2
  roles/databases/postgresql/templates/postgres_statefulset.yaml.j2
  roles/device-manager/templates/device_manager_deployment.yaml.j2
  roles/flowbroker/templates/flowbroker_deployment.yaml.j2
  roles/gui/templates/gui_deployment.yaml.j2
  roles/history/templates/history_deployment.yaml.j2
  roles/image-manager/templates/image_manager_deployment.yaml.j2
  roles/iotagent-lwm2m/templates/iotagent_lwm2m_deployment.yaml.j2
  roles/iotagent-mosca/templates/iotagent_mosca_deployment.yaml.j2
  roles/k2v-bridge/templates/k2v_bridge_cluster.yaml.j2
  roles/kafka-loopback/templates/kafka_loopback_cluster.yaml.j2
  roles/kafka-ws/templates/kafka_ws_deployment.yaml.j2
  roles/kafka-ws/templates/kafka_ws_redis_statefulset.yaml.j2
  roles/kafka/templates/kafka_statefulset.yaml.j2
  roles/kafka2ftp/templates/kafk2ftp_deployment.yaml.j2
  roles/metrics/tasks/main.yaml
  roles/metrics/templates/0prometheus-operator-deployment.yaml.j2
  roles/metrics/templates/grafana-deployment.yaml.j2
  roles/metrics/templates/kube-state-metrics-deployment.yaml.j2
  roles/metrics/templates/prometheus-servicelprometheus.yaml.j2
  roles/minio/templates/minio_statefulset.yaml.j2
  roles/persister/templates/persister_deployment.yaml.j2
  roles/rabbitmq/templates/rabbitmq_deployment.yaml.j2
  roles/v2k-bridge/templates/v2k_bridge_cluster.yaml.j2
  roles/vernemq/templates/z_vernemq_cluster.yaml.j2
  roles/x509-identity-mgmt/templates/x509_identity_mgmt_deployment.yaml.j2
  roles/zookeeper/templates/zk_statefulset.yaml.j2
Labels: Type:Enhancement

#56 GUI V2 deployment
  deploy.yaml
  docs/vars.md
  inventories/example_local/group_vars/dojot-k8s/dojot.yaml
  roles/apigw/templates/apigw_routes_config_map.yaml.j2
  roles/gui-v2/defaults/main.yaml
  roles/gui-v2/tasks/main.yaml
  roles/gui-v2/templates/gui_deployment.yaml.j2
  roles/gui-v2/templates/gui_service.yaml.j2
Labels: Type:Feature

#52 [feature] Add Locust Exporter
  docs/vars.md
  inventories/example_local/group_vars/all/dojot.yaml
  roles/apigw/templates/apigw_deployment.yaml.j2
  roles/apigw/templates/apigw_migration_job.yaml.j2
  roles/apigw/templates/apigw_migration_up_job.yaml.j2
  roles/apigw/templates/apigw_routes_config.yaml.j2
  roles/auth/templates/auth_deployment.yaml.j2
  roles/backstage/templates/backstage_deployment.yaml.j2
  roles/cron/templates/cron_deployment.yaml.j2
  roles/data-broker/templates/data_broker_deployment.yaml.j2
  roles/data-broker/templates/data_broker_redis_deployment.yaml.j2
  roles/data-manager/templates/data_manager_deployment.yaml.j2
  roles/databases/mongodb/templates/mongodb_statefulset.yaml.j2
  roles/databases/postgresql/templates/postgres_statefulset.yaml.j2
  roles/device-manager/templates/device_manager_deployment.yaml.j2
  roles/flowbroker/templates/flowbroker_deployment.yaml.j2
  roles/gui/templates/gui_deployment.yaml.j2
  roles/haproxy/templates/haproxy.cfg.j2
  roles/history/templates/history_deployment.yaml.j2
  roles/image-manager/templates/image_manager_deployment.yaml.j2
  roles/iotagent-lwm2m/templates/iotagent_lwm2m_deployment.yaml.j2
  roles/iotagent-mosca/templates/iotagent_mosca_deployment.yaml.j2
  roles/k2v-bridge/templates/k2v_bridge_cluster.yaml.j2
  roles/kafka-loopback/templates/kafka_loopback_cluster.yaml.j2
  roles/kafka-ws/templates/kafka_ws_deployment.yaml.j2
  roles/kafka-ws/templates/kafka_ws_redis_statefulset.yaml.j2
  roles/kafka/templates/kafka_statefulset.yaml.j2
  roles/kafka2ftp/templates/kafk2ftp_deployment.yaml.j2
  roles/metrics/tasks/main.yaml
  roles/metrics/templates/0prometheus-operator-deployment.yaml.j2
  roles/metrics/templates/grafana-dashboardDefinitions.yaml
  roles/metrics/templates/grafana-deployment.yaml.j2
  roles/metrics/templates/kube-state-metrics-deployment.yaml.j2
  roles/metrics/templates/locust/endpoint.yaml.j2
  roles/metrics/templates/locust/service.yaml.j2
  roles/metrics/templates/locust/serviceMonitor.yaml.j2
  roles/metrics/templates/prometheus-servicelprometheus.yaml.j2
  roles/minio/templates/minio_statefulset.yaml.j2
  roles/persister/templates/persister_deployment.yaml.j2
  roles/rabbitmq/templates/rabbitmq_deployment.yaml.j2
  roles/v2k-bridge/templates/v2k_bridge_cluster.yaml.j2
  roles/vernemq/templates/z_vernemq_cluster.yaml.j2
  roles/x509-identity-mgmt/templates/x509_identity_mgmt_deployment.yaml.j2
  roles/zookeeper/templates/zk_statefulset.yaml.j2
Labels: Type:Feature

#55 Allow choosing VerneMQ, Mosca or LWM2M on dojot deploy
  deploy.yaml
Labels: Type:Enhancement

#61 Correct identation
  roles/databases/mongodb/templates/mongodb_statefulset.yaml.j2
  roles/x509-identity-mgmt/templates/x509_identity_mgmt_deployment.yaml.j2
Labels: Type:Bug
